import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/home/Navbar";
import Footer from "@/components/home/Footer";
import ThemeContext from "@/components/shared/ThemeProviders";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeContext>
          <Navbar />
          {children}
          <Footer />
        </ThemeContext>
      </body>
    </html>
  );
}
